# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: publishing maven

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - 'main'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: central
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - id: install-secret-key
      name: Install gpg secret key
      run: |
        # Install gpg secret key
        cat <(echo -e "${{ secrets.SECRET_KEY }}" | gpg --batch --import
        # Verify gpg secret key
        gpg --list-secret-keys --keyid-format LONG
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: |
        mvn \
          --no-transfer-progress \
          --batch-mode \
          -Dgpg.passphrase=${{ secrets.SECRET_PASSWORD }} \
          clean deploy
      env:
        MAVEN_USERNAME: sJOOzga8
        MAVEN_PASSWORD: 91zeTUpcmUjz/DaJaVTObaboCyfImTV1BY+tFJwRt4+i
